version: 2
publish: &publish
  working_directory: ~/my-app
  docker:
    - image: cimg/node:14.16.0
  steps:
    - checkout

    - run:
        name: Increase Node max memory
        command: export NODE_OPTIONS=--max-old-space-size=4096

    - run:
        name: Installing dependencies
        command: npm ci

    - run:
        name: Run tests
        command: npm run test:cov

    - run:
        name: Upload code coverage
        command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

    - run:
        name: Install expo-optimize dependency
        command: npm install sharp-cli

    - run:
        name: Optimize assets
        command: npx expo-optimize ~/my-app

    - run:
        name: Login into Expo
        command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD

    - run:
        name: Publish to Expo
        command: npx expo-cli publish --max-old-space-size=4096 --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL

jobs:
  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_dependabot:
    environment:
      EXPO_RELEASE_CHANNEL: dependabot
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
  version: 2
  build_test_publish:
    jobs:
      - publish_to_expo_dev:
          filters:
            branches:
              ignore: main
      - publish_to_expo_dependabot:
          filters:
            branches:
              only: dependabot*
      - publish_to_expo_prod:
          filters:
            branches:
              only: main
